# Dockerfile
FROM python:3.8
ARG VERSION

RUN pip install concrete-ml astor
WORKDIR /app

# VERSION 변수를 사용하여 특정 버전의 ConcreteMLTransformer.py 복사
COPY ../python/convert/zama/${VERSION}/ConcreteMLTransformer.py /app

CMD ["python", "/app/ConcreteMLTransformer.py"]

